-- This file has been split into separate files:
-- scripts/001_create_tables.sql - Create all tables
-- scripts/002_enable_rls.sql - Enable RLS and create policies
-- scripts/003_seed_data.sql - Seed initial data
